openapi: 3.1.0
x-stoplight:
  id: 1wca1b2gaocci
info:
  title: lkjghudhg
  version: '1.0'
  description: hggg jgbkb
  summary: bnmbj i
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
      x-stoplight:
        id: khrcvky3a8t4m
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
      x-stoplight:
        id: 4nrfkarguhxwp
    put:
      summary: Your PUT endpoint
      tags: []
      responses: {}
      operationId: put-users-userId
      x-stoplight:
        id: fbe1w639h7swv
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      x-stoplight:
        id: yi6lu2cicky20
  '/gkbjgbg/{gkggk}/gggtre/{torotojojg}/ljjsoijrjirf/{frloijeijirjeeiojoroogjtojgt}/dmdkmgkdmgk':
    parameters:
      - schema:
          type: string
        name: gkggk
        in: path
        required: true
      - schema:
          type: string
        name: torotojojg
        in: path
        required: true
      - schema:
          type: string
        name: frloijeijirjeeiojoroogjtojgt
        in: path
        required: true
      - schema:
          type: string
        name: gkggk
        in: path
        required: true
      - schema:
          type: string
        name: torotojojg
        in: path
        required: true
      - schema:
          type: string
        name: frloijeijirjeeiojoroogjtojgt
        in: path
        required: true
      - schema:
          type: string
        name: gkggk
        in: path
        required: true
      - schema:
          type: string
        name: torotojojg
        in: path
        required: true
      - schema:
          type: string
        name: frloijeijirjeeiojoroogjtojgt
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-gkbjgbg-gkggk-gggtre-torotojojg-ljjsoijrjirf-frloijeijirjeeiojoroogjtojgt-dmdkmgkdmgk
      x-stoplight:
        id: 14rordgdsoybo
      description: mvjf
    patch:
      summary: Your PATCH endpoint
      tags: []
      responses: {}
      operationId: patch-gkbjgbg-gkggk-gggtre-torotojojg-ljjsoijrjirf-frloijeijirjeeiojoroogjtojgt-dmdkmgkdmgk
      x-stoplight:
        id: a8qnb5d76ymtq
      description: n nn
    head:
      summary: Your HEAD endpoint
      tags: []
      responses: {}
      operationId: head-gkbjgbg-gkggk-gggtre-torotojojg-ljjsoijrjirf-frloijeijirjeeiojoroogjtojgt-dmdkmgkdmgk
      x-stoplight:
        id: aqmr6lbog4kl4
      description: nbnjjnj
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: 8gyl6r0o5stor
        firstName:
          type: string
          x-stoplight:
            id: ln06tafus0fkt
        lastName:
          type: string
          x-stoplight:
            id: g73hafomdp95e
        email:
          type: string
          format: email
          x-stoplight:
            id: 404f8dp1zgr3v
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
          x-stoplight:
            id: bl5d3afokdhw8
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
          x-stoplight:
            id: vl7fo3l29knuq
        createDate:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: 9u8r83x2l2f6q
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
      x-stoplight:
        id: h6ni0l1x9opfz
